spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/catcat?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&allowPublicKeyRetrieval=true
    username: qin
    password: 7d3aa8d353b7848d
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 6 # 最大连接数
      minimum-idle: 2 # 最小空闲连接数
      idle-timeout: 60000 # 空闲连接超时时间 60秒
      connection-timeout: 5000 # 5秒内未获取到连接则报错
      max-lifetime: 1800000 # 连接最大存活时间为 30 分钟
  thymeleaf:
    cache: true # 开发时关闭缓存，不然看不到实时页面
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: Un4kHY7C6gMJkjwKRVfZ
# MyBatis 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# JWT 配置
jwt:
  secret: XnpcgH6NWZRJ+77sEAXst0B0BDnOCbF97M08ZdX/OAE=
  expiration: 10800000 # 3小时

# Tomcat 配置
server:
  tomcat:
    max-http-form-post-size: 5242880
    threads:
      max: 100
      min-spare: 10
    max-connections: 200
    accept-count: 100

# Swagger 相关配置
springdoc:
  group-configs:
    - group: 接口文档
      packages-to-scan: com.qin.catcat.unite.controller

# 启用缓存调试日志
logging:
  level:
    # org.springframework.cache: DEBUG
    # root: DEBUG  # 根日志级别
    # com.qin.catcat: DEBUG  # 项目包的日志级别
    # org.springframework: INFO  # Spring框架的日志级别
    org.springframework.cache: INFO
    root: INFO
    com.qin.catcat: INFO
    org.springframework: WARN
# 上传的图片存储的位置，部署时需要修改
file:
  upload-dir: E:/01-Codes/JavaCode/catcat-oos/uploads/pics
# 七牛云的配置
qiniu:
  access-key: FvZbXvCH0RyNyxE_8glWs0AJMTos7IvQoXeaWglA
  secret-key: b2CrZvzYP6CtCeHTFUz0qD8RnfXp2uF_wsZPAngE
  bucket: iur-blog
  upload-url: https://cdn.luckyiur.com/catcat/post_pics/