# # swagger相关配置
# springdoc:
#     group-configs:
#     - group: 接口文档
#       packages-to-scan: com.qin.catcat.unite.controller
# knife4j:
#     enable: true
#     setting:
#         language: zh_cn

# #mysql配置
# spring:
#   datasource:
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     url: jdbc:mysql://localhost:3306/catcat?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&allowPublicKeyRetrieval=true
#     # 开发账号密码
#     # username: root
#     # password:
#     # 部署测试账号密码
#     username: qin
#     password: 7d3aa8d353b7848d
#     type: com.zaxxer.hikari.HikariDataSource
#     hikari:
#       mmaximum-pool-size: 15
#       minimum-idle: 5
#       idle-timeout: 30000
#   thymeleaf:
#     cache: false # 开发时关闭缓存，不然看不到实时页面
#   servlet:
#     multipart: #配置 Spring Boot 的上传文件大小限制
#       max-file-size: 10MB
#       max-request-size: 10MB

# #mybatis 分页插件
# pagehelper:
#   helperDialect: mysql
#   reasonable: true
#   supportMethodsArguments: true
#   params: count=countSql

# jwt:
#   secret: XnpcgH6NWZRJ+77sEAXst0B0BDnOCbF97M08ZdX/OAE=
#   expiration: 3600000 #1小时


# # 配置 Tomcat 
# server:
#   tomcat:
#     max-http-form-post-size: 10485760  # 设置最大上传大小为10MB

# spring:
#   application:
#     name: catcat
#   mvc:
#     pathmatch:
#       matching-strategy: ANT_PATH_MATCHER
#   data:
#     redis:
#       host: localhost
#       port: 6379
#       database: 0
#       password: 
#   cache:
#     type: redis
#   rabbitmq:
#     host: localhost
#     port: 5672
#     username: guest
#     password: guest

# knife4j:
#   enable: true

# # jwt 配置
# # jwt:
# #   secret: your_secret_key_here
# #   expiration: 86400000 # Token 过期时间，单位为毫秒，这里设置为一天

# # spring:
# #   security:
# #     user:
# #       name: user
# #       password: aaaa
# #       password: $2a$10$/rY06jfwvcFq1KQcVbb8Ce76bSQ0bmMY3XzvFzxs6GVVDjHH7vS8u

# pagehelper:
#   propertyName: propertyValue
#   reasonable: false
#   defaultCount: true

# # 启用缓存调试日志
# logging:
#   level:
#     org.springframework.cache: DEBUG

# # 开发时关闭缓存，不然看不到实时页面
# # thymeleaf:
# #   cache: false

# # elk 日志
# # logging:
# #   config: classpath:logback-spring.xml

# # 上传的图片存储的位置，部署时需要修改
# file:
#   upload-dir: E:/01-Codes/JavaCode/catcat-oos/uploads/pics

#-------------------------------------------------------------------------

spring:
  application:
    name: catcat
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/catcat?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&allowPublicKeyRetrieval=true
    username: qin
    password: 7d3aa8d353b7848d
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  thymeleaf:
    cache: false # 开发时关闭缓存，不然看不到实时页面
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: 
  cache:
    type: redis
  # rabbitmq:
  #   host: localhost
  #   port: 5672
  #   username: guest
  #   password: guest
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: Un4kHY7C6gMJkjwKRVfZ
# MyBatis 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# JWT 配置
jwt:
  secret: XnpcgH6NWZRJ+77sEAXst0B0BDnOCbF97M08ZdX/OAE=
  expiration: 3600000 # 1小时

# Tomcat 配置
server:
  tomcat:
    max-http-form-post-size: 10485760 # 设置最大上传大小为10MB

# Swagger 相关配置
springdoc:
  group-configs:
    - group: 接口文档
      packages-to-scan: com.qin.catcat.unite.controller

# 启用缓存调试日志
logging:
  level:
    org.springframework.cache: DEBUG
    root: DEBUG  # 根日志级别
    com.qin.catcat: DEBUG  # 项目包的日志级别
    org.springframework: INFO  # Spring框架的日志级别
# 上传的图片存储的位置，部署时需要修改
file:
  upload-dir: E:/01-Codes/JavaCode/catcat-oos/uploads/pics
# 七牛云的配置
qiniu:
  access-key: FvZbXvCH0RyNyxE_8glWs0AJMTos7IvQoXeaWglA
  secret-key: b2CrZvzYP6CtCeHTFUz0qD8RnfXp2uF_wsZPAngE
  bucket: iur-blog
  upload-url: https://cdn.luckyiur.com/catcat/post_pics/