# swagger相关配置
springdoc:
    group-configs:
    - group: 接口文档
      packages-to-scan: com.qin.catcat.unite.controller
knife4j:
    enable: true
    setting:
        language: zh_cn

#mysql配置
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/catcat?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&allowPublicKeyRetrieval=true
        username: root
        password: 
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            mmaximum-pool-size: 15
            minimum-idle: 5
            idle-timeout: 30000

# # MyBatis Plus 的配置
# mybatis-plus:
#   # mybatis 配置文件的路径
#   # config-location: "classpath:mybatis/mybatis.config"
#   # mapper 映射文件的路径，可以有多个 
#   mapper-locations:
#     - "classpath*:mappers/**/*.xml"

